// Hiérarchie administrative du Cambodge + table d'alias de romanisation (§5.2).
// Format : [slug, level, parentSlug, {fr,en,zh,km}, [alias…], [lng,lat]]
// Les alias sont le point critique du produit : sans eux, environ un tiers des
// recherches textuelles ne renvoient rien. Ils sont enrichis manuellement à
// partir des logs de `search_misses`.

const P = "province", D = "district", C = "commune", N = "neighborhood";

export const locations = [
  // ---------------- Provinces ----------------
  ["phnom-penh", P, null, { fr: "Phnom Penh", en: "Phnom Penh", zh: "金边", km: "ភ្នំពេញ" },
    ["phnom penh", "phnompenh", "pnom penh", "phnum penh", "phnum pénh", "pp", "金边", "金邊", "ភ្នំពេញ"], [104.9160, 11.5564]],
  ["preah-sihanouk", P, null, { fr: "Preah Sihanouk", en: "Preah Sihanouk", zh: "西哈努克", km: "ព្រះសីហនុ" },
    ["sihanoukville", "sihanouk ville", "shv", "kampong som", "kompong som", "preah sihanouk", "西哈努克", "西港", "ក្រុងព្រះសីហនុ", "ព្រះសីហនុ"], [103.5230, 10.6270]],
  ["siem-reap", P, null, { fr: "Siem Reap", en: "Siem Reap", zh: "暹粒", km: "សៀមរាប" },
    ["siem reap", "siemreap", "siemréab", "siem riep", "sr", "angkor", "暹粒", "សៀមរាប"], [103.8555, 13.3622]],
  ["battambang", P, null, { fr: "Battambang", en: "Battambang", zh: "马德望", km: "បាត់ដំបង" },
    ["battambang", "batdambang", "battambong", "马德望", "បាត់ដំបង"], [103.1994, 13.0957]],
  ["kampot", P, null, { fr: "Kampot", en: "Kampot", zh: "贡布", km: "កំពត" },
    ["kampot", "kampote", "贡布", "កំពត"], [104.1810, 10.6104]],
  ["kep", P, null, { fr: "Kep", en: "Kep", zh: "白马", km: "កែប" },
    ["kep", "krong kep", "白马", "កែប"], [104.3167, 10.4833]],
  ["kandal", P, null, { fr: "Kandal", en: "Kandal", zh: "干丹", km: "កណ្ដាល" },
    ["kandal", "干丹", "កណ្ដាល"], [104.9500, 11.4000]],
  ["koh-kong", P, null, { fr: "Koh Kong", en: "Koh Kong", zh: "戈公", km: "កោះកុង" },
    ["koh kong", "kohkong", "戈公", "កោះកុង"], [103.0000, 11.6150]],
  ["kampong-cham", P, null, { fr: "Kampong Cham", en: "Kampong Cham", zh: "磅湛", km: "កំពង់ចាម" },
    ["kampong cham", "kompong cham", "磅湛", "កំពង់ចាម"], [105.4500, 11.9900]],
  ["kampong-speu", P, null, { fr: "Kampong Speu", en: "Kampong Speu", zh: "磅士卑", km: "កំពង់ស្ពឺ" },
    ["kampong speu", "kompong speu", "磅士卑", "កំពង់ស្ពឺ"], [104.5200, 11.4500]],
  ["kampong-thom", P, null, { fr: "Kampong Thom", en: "Kampong Thom", zh: "磅同", km: "កំពង់ធំ" },
    ["kampong thom", "kompong thom", "磅同", "កំពង់ធំ"], [104.8900, 12.7100]],
  ["kampong-chhnang", P, null, { fr: "Kampong Chhnang", en: "Kampong Chhnang", zh: "磅清扬", km: "កំពង់ឆ្នាំង" },
    ["kampong chhnang", "kompong chhnang", "磅清扬", "កំពង់ឆ្នាំង"], [104.6700, 12.2500]],
  ["takeo", P, null, { fr: "Takéo", en: "Takeo", zh: "茶胶", km: "តាកែវ" },
    ["takeo", "takéo", "ta keo", "茶胶", "តាកែវ"], [104.7850, 10.9900]],
  ["prey-veng", P, null, { fr: "Prey Veng", en: "Prey Veng", zh: "波萝勉", km: "ព្រៃវែង" },
    ["prey veng", "波萝勉", "ព្រៃវែង"], [105.3200, 11.4900]],
  ["svay-rieng", P, null, { fr: "Svay Rieng", en: "Svay Rieng", zh: "柴桢", km: "ស្វាយរៀង" },
    ["svay rieng", "bavet", "柴桢", "ស្វាយរៀង"], [105.7900, 11.0900]],
  ["banteay-meanchey", P, null, { fr: "Banteay Meanchey", en: "Banteay Meanchey", zh: "班迭棉吉", km: "បន្ទាយមានជ័យ" },
    ["banteay meanchey", "poipet", "sisophon", "班迭棉吉", "បន្ទាយមានជ័យ"], [102.9700, 13.7500]],
  ["pursat", P, null, { fr: "Pursat", en: "Pursat", zh: "菩萨", km: "ពោធិ៍សាត់" },
    ["pursat", "pouthisat", "菩萨", "ពោធិ៍សាត់"], [103.9200, 12.5300]],
  ["kratie", P, null, { fr: "Kratié", en: "Kratie", zh: "桔井", km: "ក្រចេះ" },
    ["kratie", "kratié", "桔井", "ក្រចេះ"], [106.0200, 12.4900]],
  ["mondulkiri", P, null, { fr: "Mondolkiri", en: "Mondulkiri", zh: "蒙多基里", km: "មណ្ឌលគិរី" },
    ["mondulkiri", "mondolkiri", "sen monorom", "蒙多基里", "មណ្ឌលគិរី"], [107.1900, 12.4500]],
  ["ratanakiri", P, null, { fr: "Ratanakiri", en: "Ratanakiri", zh: "拉达那基里", km: "រតនគិរី" },
    ["ratanakiri", "rattanakiri", "banlung", "拉达那基里", "រតនគិរី"], [107.0000, 13.7300]],
  ["preah-vihear", P, null, { fr: "Preah Vihear", en: "Preah Vihear", zh: "柏威夏", km: "ព្រះវិហារ" },
    ["preah vihear", "柏威夏", "ព្រះវិហារ"], [104.9800, 13.8000]],
  ["stung-treng", P, null, { fr: "Stung Treng", en: "Stung Treng", zh: "上丁", km: "ស្ទឹងត្រែង" },
    ["stung treng", "steung treng", "上丁", "ស្ទឹងត្រែង"], [105.9700, 13.5200]],
  ["oddar-meanchey", P, null, { fr: "Oddar Meanchey", en: "Oddar Meanchey", zh: "奥多棉吉", km: "ឧត្តរមានជ័យ" },
    ["oddar meanchey", "odor meanchey", "samraong", "奥多棉吉", "ឧត្តរមានជ័យ"], [103.5200, 14.1600]],
  ["pailin", P, null, { fr: "Païlin", en: "Pailin", zh: "拜林", km: "ប៉ៃលិន" },
    ["pailin", "païlin", "拜林", "ប៉ៃលិន"], [102.6100, 12.8500]],
  ["tboung-khmum", P, null, { fr: "Tboung Khmum", en: "Tboung Khmum", zh: "特本克蒙", km: "ត្បូងឃ្មុំ" },
    ["tboung khmum", "tbong khmum", "特本克蒙", "ត្បូងឃ្មុំ"], [105.8500, 11.9000]],

  // ---------------- Khan (districts) de Phnom Penh ----------------
  ["chamkar-mon", D, "phnom-penh", { fr: "Chamkar Mon", en: "Chamkar Mon", zh: "占卡蒙区", km: "ចំការមន" },
    ["chamkar mon", "chamkarmon", "chamcar mon", "khan chamkarmon", "占卡蒙", "ចំការមន"], [104.9250, 11.5400]],
  ["daun-penh", D, "phnom-penh", { fr: "Daun Penh", en: "Daun Penh", zh: "隆边区", km: "ដូនពេញ" },
    ["daun penh", "doun penh", "don penh", "khan daun penh", "riverside", "隆边", "ដូនពេញ"], [104.9280, 11.5700]],
  ["boeng-keng-kang", D, "phnom-penh", { fr: "Boeung Keng Kang", en: "Boeung Keng Kang", zh: "BKK区", km: "បឹងកេងកង" },
    ["boeung keng kang", "boeng keng kang", "bkk", "khan bkk", "បឹងកេងកង"], [104.9220, 11.5450]],
  ["prampir-makara", D, "phnom-penh", { fr: "Prampi Makara (7 Makara)", en: "Prampir Makara (7 Makara)", zh: "一月七日区", km: "ប្រាំពីរមករា" },
    ["7 makara", "prampi makara", "prampir makara", "seven makara", "ប្រាំពីរមករា"], [104.9160, 11.5620]],
  ["tuol-kouk", D, "phnom-penh", { fr: "Toul Kork", en: "Toul Kork", zh: "都格区", km: "ទួលគោក" },
    ["toul kork", "tuol kouk", "toul kok", "tk", "tuolkork", "都格", "ទួលគោក"], [104.8990, 11.5730]],
  ["sen-sok", D, "phnom-penh", { fr: "Sen Sok", en: "Sen Sok", zh: "森速区", km: "សែនសុខ" },
    ["sen sok", "sensok", "森速", "សែនសុខ"], [104.8880, 11.5950]],
  ["mean-chey", D, "phnom-penh", { fr: "Mean Chey", en: "Mean Chey", zh: "棉芷区", km: "មានជ័យ" },
    ["mean chey", "meanchey", "棉芷", "មានជ័យ"], [104.9310, 11.5140]],
  ["russey-keo", D, "phnom-penh", { fr: "Russey Keo", en: "Russey Keo", zh: "鲁西给区", km: "ឫស្សីកែវ" },
    ["russey keo", "reussey keo", "russei keo", "ឫស្សីកែវ"], [104.9080, 11.6150]],
  ["chroy-changvar", D, "phnom-penh", { fr: "Chroy Changvar", en: "Chroy Changvar", zh: "水净华区", km: "ជ្រោយចង្វារ" },
    ["chroy changvar", "chroy chongva", "chroy changva", "peninsula", "水净华", "ជ្រោយចង្វារ"], [104.9420, 11.5980]],
  ["pou-senchey", D, "phnom-penh", { fr: "Pou Senchey", en: "Pou Senchey", zh: "菩森芷区", km: "ពោធិ៍សែនជ័យ" },
    ["pou senchey", "posenchey", "por senchey", "ពោធិ៍សែនជ័យ"], [104.8500, 11.5450]],
  ["dangkao", D, "phnom-penh", { fr: "Dangkao", en: "Dangkao", zh: "登哥区", km: "ដង្កោ" },
    ["dangkao", "dangkor", "ដង្កោ"], [104.8700, 11.4900]],
  ["chbar-ampov", D, "phnom-penh", { fr: "Chbar Ampov", en: "Chbar Ampov", zh: "甘密区", km: "ច្បារអំពៅ" },
    ["chbar ampov", "chbah ampov", "ច្បារអំពៅ"], [104.9550, 11.5300]],
  ["prek-pnov", D, "phnom-penh", { fr: "Prek Pnov", en: "Prek Pnov", zh: "波比区", km: "ព្រែកព្នៅ" },
    ["prek pnov", "preak pnov", "ព្រែកព្នៅ"], [104.8800, 11.6600]],
  ["kamboul", D, "phnom-penh", { fr: "Kamboul", en: "Kamboul", zh: "甘博区", km: "កំបូល" },
    ["kamboul", "kambol", "កំបូល"], [104.7900, 11.5100]],

  // ---------------- Sangkat / quartiers de Phnom Penh ----------------
  ["bkk1", N, "boeng-keng-kang", { fr: "BKK1", en: "BKK1", zh: "BKK1", km: "បឹងកេងកង១" },
    ["bkk1", "bkk 1", "bkk one", "b.k.k 1", "boeung keng kang 1", "boeng keng kang 1", "boeung keng kang i", "បឹងកេងកង១", "BKK一区"], [104.9219, 11.5468]],
  ["bkk2", N, "boeng-keng-kang", { fr: "BKK2", en: "BKK2", zh: "BKK2", km: "បឹងកេងកង២" },
    ["bkk2", "bkk 2", "bkk two", "boeung keng kang 2", "បឹងកេងកង២"], [104.9180, 11.5390]],
  ["bkk3", N, "boeng-keng-kang", { fr: "BKK3", en: "BKK3", zh: "BKK3", km: "បឹងកេងកង៣" },
    ["bkk3", "bkk 3", "bkk three", "boeung keng kang 3", "បឹងកេងកង៣"], [104.9130, 11.5410]],
  ["tonle-bassac", N, "chamkar-mon", { fr: "Tonlé Bassac", en: "Tonle Bassac", zh: "巴萨", km: "ទន្លេបាសាក់" },
    ["tonle bassac", "tonlé bassac", "bassac", "tonle basak", "ទន្លេបាសាក់"], [104.9310, 11.5470]],
  ["koh-pich", N, "chamkar-mon", { fr: "Koh Pich (Diamond Island)", en: "Koh Pich (Diamond Island)", zh: "钻石岛", km: "កោះពេជ្រ" },
    ["koh pich", "kohpich", "diamond island", "koh puch", "钻石岛", "កោះពេជ្រ"], [104.9420, 11.5440]],
  ["tuol-tumpung", N, "chamkar-mon", { fr: "Toul Tom Poung (Marché russe)", en: "Toul Tom Poung (Russian Market)", zh: "俄罗斯市场", km: "ទួលទំពូង" },
    ["toul tom poung", "tuol tumpung", "toul tumpoung", "russian market", "russey market", "psar toul tom poung", "俄罗斯市场", "ទួលទំពូង"], [104.9160, 11.5340]],
  ["boeung-trabek", N, "chamkar-mon", { fr: "Boeung Trabek", en: "Boeung Trabek", zh: "波托贝", km: "បឹងត្របែក" },
    ["boeung trabek", "boeng trabek", "bassac garden", "បឹងត្របែក"], [104.9260, 11.5320]],
  ["tuol-svay-prey", N, "boeng-keng-kang", { fr: "Toul Svay Prey", en: "Toul Svay Prey", zh: "都斯雷", km: "ទួលស្វាយព្រៃ" },
    ["toul svay prey", "tuol svay prey", "toul sleng", "ទួលស្វាយព្រៃ"], [104.9170, 11.5490]],
  ["phsar-thmei", N, "daun-penh", { fr: "Phsar Thmey (Marché central)", en: "Phsar Thmey (Central Market)", zh: "中央市场", km: "ផ្សារថ្មី" },
    ["phsar thmei", "phsar thmey", "psar thmey", "central market", "new market", "中央市场", "ផ្សារថ្មី"], [104.9200, 11.5690]],
  ["wat-phnom", N, "daun-penh", { fr: "Wat Phnom", en: "Wat Phnom", zh: "塔山寺", km: "វត្តភ្នំ" },
    ["wat phnom", "watphnom", "srah chak", "塔山", "វត្តភ្នំ"], [104.9260, 11.5760]],
  ["chey-chumneas", N, "daun-penh", { fr: "Chey Chumneas", en: "Chey Chumneas", zh: "皇宫区", km: "ជ័យជំនះ" },
    ["chey chumneas", "chey chumnas", "royal palace", "riverside", "sisowath quay", "ជ័យជំនះ"], [104.9310, 11.5620]],
  ["boeung-raing", N, "daun-penh", { fr: "Boeung Raing", en: "Boeung Raing", zh: "文化中心区", km: "បឹងរាំង" },
    ["boeung raing", "boeng reang", "បឹងរាំង"], [104.9230, 11.5730]],
  ["veal-vong", N, "prampir-makara", { fr: "Veal Vong (Olympique)", en: "Veal Vong (Olympic)", zh: "奥林匹克", km: "វាលវង់" },
    ["veal vong", "olympic", "olympic stadium", "orussey", "奥林匹克", "វាលវង់"], [104.9160, 11.5560]],
  ["monourom", N, "prampir-makara", { fr: "Monourom", en: "Monourom", zh: "莫努隆", km: "មនោរម្យ" },
    ["monourom", "mono rom", "មនោរម្យ"], [104.9130, 11.5660]],
  ["boeung-salang", N, "tuol-kouk", { fr: "Boeung Salang", en: "Boeung Salang", zh: "波萨朗", km: "បឹងសាឡាង" },
    ["boeung salang", "boeng salang", "បឹងសាឡាង"], [104.8950, 11.5860]],
  ["phsar-depo", N, "tuol-kouk", { fr: "Phsar Depo", en: "Phsar Depo", zh: "德宝市场", km: "ផ្សារដេប៉ូ" },
    ["phsar depo", "psar depo", "depot market", "ផ្សារដេប៉ូ"], [104.9040, 11.5670]],
  ["boeung-kak", N, "tuol-kouk", { fr: "Boeung Kak", en: "Boeung Kak", zh: "波哥湖", km: "បឹងកក់" },
    ["boeung kak", "boeng kak", "boeung kak 1", "បឹងកក់"], [104.9120, 11.5840]],
  ["teuk-thla", N, "sen-sok", { fr: "Teuk Thla", en: "Teuk Thla", zh: "德拉区", km: "ទឹកថ្លា" },
    ["teuk thla", "tuek thla", "toek thla", "ទឹកថ្លា"], [104.8880, 11.5760]],
  ["phnom-penh-thmey", N, "sen-sok", { fr: "Phnom Penh Thmey", en: "Phnom Penh Thmey", zh: "新金边", km: "ភ្នំពេញថ្មី" },
    ["phnom penh thmey", "pp thmey", "new phnom penh", "新金边", "ភ្នំពេញថ្មី"], [104.8930, 11.6010]],
  ["chrang-chamres", N, "russey-keo", { fr: "Chrang Chamres", en: "Chrang Chamres", zh: "章昌", km: "ច្រាំងចំរេះ" },
    ["chrang chamres", "chrang chamreh", "ច្រាំងចំរេះ"], [104.8990, 11.6260]],
  ["chroy-changvar-village", N, "chroy-changvar", { fr: "Chroy Changvar (presqu'île)", en: "Chroy Changvar Peninsula", zh: "水净华半岛", km: "ជ្រោយចង្វារ" },
    ["chroy changvar peninsula", "peninsula", "chroy changva", "ជ្រោយចង្វារ"], [104.9450, 11.5900]],
  ["stueng-mean-chey", N, "mean-chey", { fr: "Steung Meanchey", en: "Steung Meanchey", zh: "斯登棉芷", km: "ស្ទឹងមានជ័យ" },
    ["steung meanchey", "stung meanchey", "steung mean chey", "ស្ទឹងមានជ័យ"], [104.9130, 11.5220]],
  ["chak-angre", N, "mean-chey", { fr: "Chak Angre", en: "Chak Angre", zh: "扎盎雷", km: "ចាក់អង្រែ" },
    ["chak angre", "chak angre leu", "chak angre krom", "ចាក់អង្រែ"], [104.9330, 11.5090]],

  // ---------------- Siem Reap ----------------
  ["krong-siem-reap", D, "siem-reap", { fr: "Ville de Siem Reap", en: "Siem Reap City", zh: "暹粒市", km: "ក្រុងសៀមរាប" },
    ["siem reap city", "krong siem reap", "暹粒市", "ក្រុងសៀមរាប"], [103.8555, 13.3622]],
  ["svay-dangkum", N, "krong-siem-reap", { fr: "Svay Dangkum", en: "Svay Dangkum", zh: "斯瓦当昆", km: "ស្វាយដង្គំ" },
    ["svay dangkum", "svay dangkom", "pub street", "old market area", "ស្វាយដង្គំ"], [103.8570, 13.3560]],
  ["sala-kamreuk", N, "krong-siem-reap", { fr: "Sala Kamreuk", en: "Sala Kamreuk", zh: "萨拉甘罗", km: "សាលាកំរើក" },
    ["sala kamreuk", "sala kamroeuk", "wat bo", "wat bo village", "សាលាកំរើក"], [103.8620, 13.3520]],
  ["slor-kram", N, "krong-siem-reap", { fr: "Slor Kram", en: "Slor Kram", zh: "斯罗克兰", km: "ស្លក្រាម" },
    ["slor kram", "sla kram", "slorkram", "ស្លក្រាម"], [103.8640, 13.3680]],
  ["kouk-chak", N, "krong-siem-reap", { fr: "Kouk Chak", en: "Kouk Chak", zh: "国扎", km: "គោកចក" },
    ["kouk chak", "kok chak", "គោកចក"], [103.8420, 13.3660]],

  // ---------------- Sihanoukville ----------------
  ["krong-preah-sihanouk", D, "preah-sihanouk", { fr: "Ville de Sihanoukville", en: "Sihanoukville City", zh: "西哈努克市", km: "ក្រុងព្រះសីហនុ" },
    ["sihanoukville city", "krong preah sihanouk", "西港市", "ក្រុងព្រះសីហនុ"], [103.5230, 10.6270]],
  ["sangkat-buon", N, "krong-preah-sihanouk", { fr: "Sangkat 4", en: "Sangkat 4", zh: "四区", km: "សង្កាត់លេខ៤" },
    ["sangkat 4", "sangkat buon", "sangkat lekh buon", "四区", "សង្កាត់លេខ៤"], [103.5150, 10.6180]],
  ["otres", N, "krong-preah-sihanouk", { fr: "Otres", en: "Otres", zh: "奥特斯海滩", km: "អូរត្រេះ" },
    ["otres", "otres beach", "otres 1", "otres 2", "奥特斯", "អូរត្រេះ"], [103.4880, 10.5860]],
  ["ochheuteal", N, "krong-preah-sihanouk", { fr: "Ochheuteal", en: "Ochheuteal", zh: "奥切迭海滩", km: "អូរជើងថ្ម" },
    ["ochheuteal", "occheuteal", "ochheuteal beach", "serendipity", "អូរជើងថ្ម"], [103.5230, 10.6040]],
  ["victory-hill", N, "krong-preah-sihanouk", { fr: "Victory Hill", en: "Victory Hill", zh: "胜利山", km: "ភ្នំវិជ័យ" },
    ["victory hill", "weather station hill", "victory beach", "胜利山", "ភ្នំវិជ័យ"], [103.4990, 10.6360]],
  ["independence-beach", N, "krong-preah-sihanouk", { fr: "Plage de l'Indépendance", en: "Independence Beach", zh: "独立海滩", km: "ឆ្នេរឯករាជ្យ" },
    ["independence beach", "independance beach", "独立海滩", "ឆ្នេរឯករាជ្យ"], [103.5060, 10.6110]],

  // ---------------- Autres villes ----------------
  ["krong-kampot", D, "kampot", { fr: "Ville de Kampot", en: "Kampot City", zh: "贡布市", km: "ក្រុងកំពត" },
    ["kampot city", "krong kampot", "kampong bay", "贡布市", "ក្រុងកំពត"], [104.1810, 10.6104]],
  ["krong-battambang", D, "battambang", { fr: "Ville de Battambang", en: "Battambang City", zh: "马德望市", km: "ក្រុងបាត់ដំបង" },
    ["battambang city", "svay por", "rattanak", "马德望市", "ក្រុងបាត់ដំបង"], [103.1994, 13.0957]],
  ["krong-kep", D, "kep", { fr: "Ville de Kep", en: "Kep City", zh: "白马市", km: "ក្រុងកែប" },
    ["kep city", "krong kep", "白马市", "ក្រុងកែប"], [104.3167, 10.4833]],
  ["takhmao", D, "kandal", { fr: "Ta Khmau", en: "Ta Khmau", zh: "达克茂", km: "តាខ្មៅ" },
    ["ta khmau", "takhmao", "takhmau", "តាខ្មៅ"], [104.9450, 11.4830]],
];
